import "dotenv/config";
import express from 'express';
import { connectDB } from './config/db.mjs';
import http from 'http';
import { Server } from 'socket.io';
import authRoutes from './routes/auth.js';
import guestRoutes from './routes/guest.js';
import bookingRoutes from './routes/booking.js';
import invoiceRoutes from './routes/invoice.js';
import housekeepingRoutes from './routes/housekeeping.js';
import maintenanceRoutes from './routes/maintenance.js';
import roomRoute from './routes/room.js';
import userManagementRoutes from './routes/userManagement.js';
import cors from 'cors';
await connectDB();
const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static('public'));
const server = http.createServer(app);
const io = new Server(server, { cors: { origin: '*' } });
app.set('io', io);
app.use('/api/auth', authRoutes);
app.use('/api/guest', guestRoutes);
app.use('/api/bookings', bookingRoutes);
app.use('/api/invoices', invoiceRoutes);
app.use('/api/housekeeping', housekeepingRoutes);
app.use('/api/maintenance', maintenanceRoutes);
app.use('/api/rooms', roomRoute);
app.use('/api/usermanagement', userManagementRoutes);
const PORT = process.env.PORT || 3000;
io.on('connection', socket => {
    console.log('Client connected:', socket.id);
});
app.get('/', (req, res) => res.send('Hello from Luxurystay User!'));
server.listen(PORT, () => {
    console.log(`🚀 Server + Socket.IO running on port ${PORT}`);
});
